"""Render complete aggregate-feature tables from the report's frozen run (stdlib only)."""
from pathlib import Path
import hashlib
import json
import math

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'results/correlation_pipeline/reasoning-vllm-untagged-v1/analysis/unsloth--Qwen3.5-35B-A3B'
FEATURES = {
    'token_count': ('T', 'Token count'),
    'router_confidence_mean_layers': ('C', 'Router confidence'),
    'router_margin_mean_layers': ('M', 'Top-1/top-2 margin'),
    'router_selected_mass_mean_layers': ('S', 'Top-8 probability mass'),
    'router_boundary_margin_mean_layers': ('B', 'Top-8/top-9 margin'),
    'router_topk_non_topk_gap_mean_layers': ('G', 'Top-8/non-top-8 mean gap'),
    'hidden_norm_mean_layers': ('H', 'Hidden-state norm'),
    'hidden_step_distance_mean_layers': ('D', 'Hidden-state step distance'),
    'hidden_router_geometry_mean_layers': ('R', 'Hidden/router geometry'),
    'router_switch_rate_mean_layers': ('W', 'Top-1 switch rate'),
    'router_topk_overlap_mean_layers': ('O', 'Adjacent top-8 overlap'),
    'character_count': ('Ch', 'Character count'),
    'step_count': ('St', 'Step count'),
}
DATASETS = ['math500', 'aime24', 'aime25', 'olympiad', 'amc23', 'minerva']
HEADER = ' & MATH-500 & AIME24 & AIME25 & Olympiad & AMC23 & Minerva'
manifest = {}

def read(relative):
    path = SOURCE / relative
    manifest[str(path.relative_to(ROOT))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return json.loads(path.read_text())

def cell(row, key):
    value = row[key]
    assert value is not None and math.isfinite(value), row
    return f'${value:.3f}$ ({row["n_traces"]:,})'

def table(caption, label, heading, rows):
    return '\n'.join([
        r'\begingroup\scriptsize\setlength{\tabcolsep}{3pt}',
        r'\begin{longtable}{@{}lrrrrrr@{}}',
        '\\caption{' + caption + '}\\label{' + label + r'}\\',
        r'\toprule', heading + HEADER + r' \\', r'\midrule', r'\endfirsthead',
        r'\multicolumn{7}{l}{\textit{Continued from previous page}}\\',
        r'\toprule', heading + HEADER + r' \\', r'\midrule', r'\endhead',
        r'\bottomrule\endfoot', *[r if r == r'\midrule' else r + r' \\' for r in rows],
        r'\end{longtable}\endgroup', '',
    ])

base = read('correlations.json')
assert base['status'] == base['reasoning_view_analysis']['status'] == 'complete'
assert base['n_traces'] == 4647 and set(base['datasets']) == set(DATASETS)
full = read('views-v1/full/reasoning/correlations.json')
positions = [(f'Bin {i}', read(f'views-v1/position/bin_{i:02d}/correlations.json')) for i in range(10)]
positions.append(('Overflow', read('views-v1/position/overflow/correlations.json')))
for _, view in [('Full reasoning', full), *positions]:
    assert view['contract'] == full['contract']
    assert view['coverage']['traces'] == 4647

intro = r'''% Generated by generate_correlation_tables.py; do not edit numerical cells.
\section{Complete aggregate correlation tables}
\label{sec:complete-correlation-tables}
These tables expand the selected results in the main text using the same
September 10, 2026 \path{reasoning-vllm-untagged-v1} snapshot.
All tables use Qwen3.5-35B-A3B: GPTQ-Int4 generation through vLLM and
runtime-4-bit replay through the unsloth checkpoint, with selected decoder
indices 27, 34, 35, 36, 38, and 39. Generation uses temperature 0.6,
top-$p$ 0.95, and a 32,768-token completion budget. MATH-500, OlympiadBench,
and Minerva use one attempt per problem; AIME 2024/2025 and AMC 2023 use 32.
Finite trace counts appear either alongside coefficients or in a separate
row when shared by all metrics in a panel.
The unit is an attempt, including repeated attempts from the same problem.
Coefficients are descriptive: no significance markings or uncertainty
intervals are implied. Saved uncertainty estimates, where available, remain
in the source JSON files; source hashes are recorded in
\texttt{correlation\_tables\_sources.json}.

The full-reasoning view excludes final-answer tokens. Position windows are
disjoint absolute spans of one tenth of the corpus mean (12,477.026 tokens),
with an additional overflow window. Missing windows are excluded pairwise;
late windows therefore describe changing cohorts. Token counts are omitted
as position predictors. All coefficients remain subject to the length,
termination, and repeated-attempt limitations discussed in the main text.
These tables cover aggregate means, not the exploratory layerwise screen.
No class tagging is used.

\subsection{Full reasoning versus correctness}
'''
parts = [intro]
lookup = {(r['scope'], r['feature']): r for r in full['binary_correlations'] if r['target'] == 'is_correct'}
aggregate = list(FEATURES)[:11]
parts.append(table('Full reasoning: aggregate features versus whole-attempt correctness. Point-biserial $r$ (finite traces); model and protocol as specified above.', 'tab:qwen-full-all', 'Feature', [FEATURES[f][1] + ' & ' + ' & '.join(cell(lookup[d, f], 'point_biserial_r') for d in DATASETS) for f in aggregate]))
parts.append(r'\subsection{All aggregate metrics by position}')
for feature in aggregate[1:]:
    rows = []
    for name, view in positions:
        lookup = {(r['scope'], r['feature']): r for r in view['binary_correlations'] if r['target'] == 'is_correct'}
        rows.append(name + ' & ' + ' & '.join(cell(lookup[d, feature], 'point_biserial_r') for d in DATASETS))
    parts.append(table(FEATURES[feature][1] + ': position-specific point-biserial $r$ versus whole-attempt correctness (finite traces). Model and protocol as specified above.', 'tab:qwen-position-' + FEATURES[feature][0], 'Window', rows))
parts.append(r'''\subsection{Correlations organized by target metric}
Each table fixes one target metric, lists the other metrics by name in the
rows, and compares the six benchmarks in columns, matching the layout of the
correctness table. Cells give descriptive Spearman $\rho$; a separate sample
count row is used when all coefficients in a panel have the same finite count.
Self-correlations are omitted. A correlation appears under both target
orientations for ease of reading; these are the same association, not
independent results. The algebraically redundant mass/gap pair is retained
to reproduce the saved scan. Character and step counts occur only in the
entire-continuation scan; token count is excluded from position scans.
''')

def pair_panel(view, target):
    records = view['cross_feature_correlations']['trace_level']
    lookup = {(r['scope'], frozenset((r['feature_x'], r['feature_y']))): r for r in records}
    features = [f for f in FEATURES if any(f in (r['feature_x'], r['feature_y']) for r in records)]
    assert target in features
    others = [f for f in features if f != target]
    for d in DATASETS:
        assert len([r for r in records if r['scope'] == d]) == len(features) * (len(features) - 1) // 2
    counts = {d: {lookup[d, frozenset((target, f))]['n_traces'] for f in others} for d in DATASETS}
    shared = all(len(c) == 1 for c in counts.values())
    rows = []
    if shared:
        rows.append('Finite traces & ' + ' & '.join(f'{next(iter(counts[d])):,}' for d in DATASETS))
        rows.append(r'\midrule')
    for feature in others:
        cells = []
        for d in DATASETS:
            record = lookup[d, frozenset((target, feature))]
            value = cell(record, 'spearman_rho')
            cells.append(value.split(' (')[0] if shared else value)
        rows.append(FEATURES[feature][1] + ' & ' + ' & '.join(cells))
    return rows

for name, view, features, prefix in [
    ('Entire continuation', base, list(FEATURES), 'continuation'),
    ('Full reasoning', full, aggregate, 'reasoning'),
]:
    parts.append(r'\subsubsection{' + name + '}')
    for target in features:
        title = name + ': metrics versus ' + FEATURES[target][1].lower()
        parts.append(table(title + '. Spearman $\\rho$; model and protocol as specified above.',
                           'tab:qwen-target-' + prefix + '-' + FEATURES[target][0], 'Feature', pair_panel(view, target)))

parts.append(r'''\subsubsection{Position windows, organized by target}
Each table keeps the same target throughout. Separate panels give the
non-cumulative windows, with metrics in rows and benchmarks in columns.
''')
for target in aggregate[1:]:
    rows = []
    for name, view in positions:
        rows.append(r'\multicolumn{7}{l}{\textbf{' + name + '}}')
        rows.extend(pair_panel(view, target))
        rows.append(r'\midrule')
    parts.append(table('Position windows: metrics versus ' + FEATURES[target][1].lower() +
                       '. Spearman $\\rho$; model and protocol as specified above.',
                       'tab:qwen-target-position-' + FEATURES[target][0], 'Feature', rows))

(ROOT / 'report/correlation_tables.tex').write_text('\n'.join(parts))
(ROOT / 'report/correlation_tables_sources.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(f'Wrote {sum(part.count(chr(92) + "begin{longtable}") for part in parts)} tables from {len(manifest)} source files.')
